### ISSUE TITLE
Allow to link between datamodels

### ISSUE THREAD

**Issue by albireox** [sdss/datamodel#134]
It would be useful to have a way to link to a different datamodel in a description and ensure that the link points to the right address in the DSI. The URL path in the DSI seems to be

```
https://data.sdss5.org/dsi/file/select-<DATAMODEL>/<BRANCH>
```

but it's unclear if this will change once we have data releases. Ideally we could have a macro line

```yaml
general:
  name: confSummaryF
  short: File describing the targeting and parameters used to generate a configuration.
  description: A link to <link:confSummary> ...
```

that can be regex'd and replaced with the correct address, maybe at the DSI level.
