### ISSUE TITLE
How to deal with missing values in headers

### ISSUE THREAD

**Issue by ajwheeler** [sdss/datamodel#61]
The mwmVisit file from which I'm generating the datamodel doesn't have Gaia DR2 RVs.  The header of it's primary HDU contains:
```yaml
        - key: VRAD
          value: null
          comment: Gaia DR2 radial velocity [km/s]
        - key: E_VRAD
          value: null
```
This doesn't validate, but what's the correct thing to do for missing values?  Deleting the `null`s doesn't work.

(I realize that ideally I would just use an example with this info present.)
